server:
  port: 8081

spring:
  application:
    name: library
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://${LIBRARY_DB_HOST}:${LIBRARY_DB_PORT}/${LIBRARY_DB_NAME}?User${USER}
    username: ${LIBRARY_DB_USERNAME}
    password: ${LIBRARY_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 0
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false